### ISSUE TITLE
After slide Clear, no data until "reload Script"

### ISSUE THREAD

**Issue by j0nvinci** [AronHetLam/stagedisplay-viewer-OBS-script#3]
We started using you script today for a lower third. I noticed if the slide is clear/empty for a while, lets say about 3-5 minutes, the next actual slide won't appear in the text source until I manually reload the script via OBS script menu. After reloading script, functionality resumes until the next time the screen sits clear/empty. If I leave text on the slide the script operates fully the entire time.

OBS PC:
OBS 25.0.1
Windows 10 x64
Python 3.6.6 x64

Propresenter PC:
ProPresenter 6.1.6.2
Windows 10 x64

**Comment by AronHetLam** [comment]
I can't recreate the issue on my machine, but also I run both applications on the same host.

Does your Scriptlog in OBS give any hint towards the script disconnecting from PP after a while of receiving blank slides?

Later I might be able to setup a multisystem setup to test with.

**Comment by j0nvinci** [comment]
Unfortunately not. While not working, the last line of the log still says “Connected.”

I can provide you remote access to the computers in question if you’d like.

**Comment by AronHetLam** [comment]
I found a problem where it gets stuck if it disconnects. I'm working on a fix.

**Comment by AronHetLam** [comment]
Committed a fix that should handle connection losses better that it did so far. That was the problem i could recreate when running PP on a separate system. Try and see if it works for you.

**Comment by j0nvinci** [comment]
Awesome, Will do!
